const KEY='oas-teamday-v1', TEAM_KEY='oas-teamday-selected-team', cfg=window.TEAMDAY_CONFIG||{};
const answers=['X','1','X','1','2'];
const questions=[['1 · Hitta alléerna','Vilket trädslag består de gamla alléerna huvudsakligen av?',['1. Ek','X. Lind','2. Bok']],['2 · Leta efter en stjärna','Vilken annan parkanläggning skapades tillsammans med Stjärnboskén?',['1. Lövteatern','X. Rosengården','2. Kungliga ridbanan']],['3 · Engelska parken','Vem slutförde den engelska parken efter Fredrik Adolf?',['1. Drottning Victoria','X. Prinsessan Sofia Albertina','2. Drottning Josefina']],['4 · Orangeriet','Vilka två byggnader hör till Oskar och Josefinas tid?',['1. Stallet och kavaljersflygeln','X. Badhuset och Stjärnboskén','2. Lövteatern och båthuset']],['5 · Trädjakten','Vilket ovanligt trädslag kan fortfarande hittas i parken?',['1. Japansk skärmtall','X. Korkek','2. Libanonceder']]];
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const remote=Boolean(cfg.url&&cfg.anonKey), apiBase=remote?`${cfg.url.replace(/\/$/,'')}/rest/v1`:'';
let syncTimer, state=JSON.parse(localStorage.getItem(KEY)||'null')||{teams:[{id:crypto.randomUUID(),name:'Lag 1',members:[{name:'',scores:[0,0,0,0,0]}]}],quizzes:[]};
state.teams.forEach(t=>{t.id??=crypto.randomUUID();t.members.forEach(m=>m.scores=[0,0,0,0,0].map((_,i)=>m.scores?.[i]||0))});
let selectedTeamId=localStorage.getItem(TEAM_KEY)||(state.teams.length===1?state.teams[0].id:'');
const setStatus=(text,kind='')=>{const el=$('#sync-status');el.textContent=text;el.className=`sync-status ${kind}`};
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));if(remote){setStatus('Sparat lokalt · synkar…','busy');clearTimeout(syncTimer);syncTimer=setTimeout(syncAll,500)}};
async function request(path,options={}){const r=await fetch(`${apiBase}/${path}`,{...options,headers:{apikey:cfg.anonKey,Authorization:`Bearer ${cfg.anonKey}`,Prefer:'return=minimal',...(options.headers||{})}});if(!r.ok)throw Error(await r.text());return r.status===204?null:r.json()}
async function syncAll(){try{for(const t of state.teams)await request('team_cards',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal','Content-Type':'application/json'},body:JSON.stringify({id:t.id,event_code:cfg.eventCode,name:t.name,members:t.members,updated_at:new Date().toISOString()})});setStatus('Synkad','ok')}catch(e){setStatus('Ej synkad · sparat lokalt','error')}}
async function loadRemote(){if(!remote){setStatus('Lokal lagring');return}try{const [teams,quizzes]=await Promise.all([request(`team_cards?event_code=eq.${encodeURIComponent(cfg.eventCode)}&order=updated_at.asc`,{headers:{Prefer:'return=representation'}}),request(`quiz_entries?event_code=eq.${encodeURIComponent(cfg.eventCode)}&order=created_at.asc`,{headers:{Prefer:'return=representation'}})]);if(teams.length)state.teams=teams.map(t=>({id:t.id,name:t.name,members:t.members}));state.quizzes=quizzes.map(q=>({id:q.id,name:q.name,correct:q.correct,tie:q.tie_break}));localStorage.setItem(KEY,JSON.stringify(state));renderTeams();renderLeaderboard();renderQuiz();setStatus('Synkad','ok')}catch(e){setStatus('Offline · lokalt läge','error')}}
function renderTeamPicker(){const picker=$('#team-picker');picker.innerHTML=state.teams.map(t=>`<option value="${t.id}">${esc(t.name||'Namnlöst lag')}</option>`).join('');picker.value=selectedTeamId;picker.onchange=e=>{selectedTeamId=e.target.value;localStorage.setItem(TEAM_KEY,selectedTeamId);$('#team-detail').innerHTML='';delete $('#team-detail').dataset.teamId;renderTeams();renderLeaderboard()}}
function renderTeams(){const list=$('#team-list');list.innerHTML='';renderTeamPicker();const team=state.teams.find(t=>t.id===selectedTeamId);if(!team){list.innerHTML='<div class="card empty">Välj ditt lag ovan för att öppna scorekortet.</div>';return}const ti=state.teams.indexOf(team),card=$('#team-template').content.cloneNode(true),el=card.querySelector('.team-card');card.querySelector('.team-number').textContent=ti+1;const name=card.querySelector('.team-name');name.value=team.name;name.oninput=e=>{team.name=e.target.value;save();renderTeamPicker();renderLeaderboard()};const members=card.querySelector('.members');const updateTotal=()=>{el.querySelector('.team-total').textContent=team.members.reduce((a,m)=>a+m.scores.reduce((x,v)=>x+(+v||0),0),0)+' p'};team.members.forEach((m,mi)=>{const row=$('#member-template').content.cloneNode(true),n=row.querySelector('.member-name');n.value=m.name;n.oninput=e=>{m.name=e.target.value;save()};row.querySelectorAll('.score').forEach(s=>{const b=+s.dataset.branch;s.value=m.scores[b]||0;s.oninput=e=>{m.scores[b]=+e.target.value||0;save();updateTotal();renderLeaderboard()}});row.querySelector('.delete-member').onclick=()=>{team.members.splice(mi,1);save();renderTeams()};members.append(row)});updateTotal();card.querySelector('.add-member').onclick=()=>{team.members.push({name:'',scores:[0,0,0,0,0]});save();renderTeams()};list.append(card)}
function renderLeaderboard(){const rows=state.teams.map(t=>({team:t,name:t.name||'Namnlöst lag',score:t.members.reduce((a,m)=>a+m.scores.reduce((x,v)=>x+(+v||0),0),0)})).sort((a,b)=>b.score-a.score);$('#leaderboard').innerHTML=rows.length?rows.map((r,i)=>{const own=r.team.id===selectedTeamId;return `<div class="ranking-row"><span class="rank">${i+1}</span><div>${own?`<button class="team-link" data-team-id="${r.team.id}"><strong>${esc(r.name)}</strong><small>${i===0?'Leder just nu · klicka för detaljer':'Ditt lag · klicka för detaljer'}</small></button>`:`<div><strong>${esc(r.name)}</strong><small>Femkamp</small></div>`}</div><strong>${r.score} p</strong></div>`}).join(''):'<div class="empty">Inga lag ännu.</div>';document.querySelectorAll('.team-link').forEach(b=>b.onclick=()=>showTeam(b.dataset.teamId))}
function showTeam(id){if(id!==selectedTeamId)return;const detail=$('#team-detail');if(detail.dataset.teamId===id){detail.innerHTML='';delete detail.dataset.teamId;return}const team=state.teams.find(t=>t.id===id);if(!team)return;const total=team.members.reduce((a,m)=>a+m.scores.reduce((x,v)=>x+(+v||0),0),0);detail.dataset.teamId=id;detail.innerHTML=`<h3>${esc(team.name||'Namnlöst lag')} · ${total} p</h3><table class="detail-table"><thead><tr><th>Deltagare</th><th>Pilbåge</th><th>Lasso</th><th>Luftpistol</th><th>Hästskor</th><th>Balans</th><th>Totalt</th></tr></thead><tbody>${team.members.map(m=>`<tr><td>${esc(m.name||'Namnlös')}</td>${m.scores.map(s=>`<td>${+s||0}</td>`).join('')}<td><strong>${m.scores.reduce((a,v)=>a+(+v||0),0)}</strong></td></tr>`).join('')}</tbody></table>`}
function renderQuiz(){const q=$('#quiz-questions');q.innerHTML=questions.map((item,i)=>`<div class="quiz-question"><h3>${item[0]} — ${item[1]}</h3><div class="options">${item[2].map((o,j)=>{const v=['1','X','2'][j];return `<label><input type="radio" name="q${i}" value="${v}"><span>${o}</span></label>`}).join('')}</div></div>`).join('');const rows=[...state.quizzes].sort((a,b)=>b.correct-a.correct||Math.abs(a.tie-12)-Math.abs(b.tie-12));$('#quiz-leaderboard').innerHTML=rows.length?rows.map((r,i)=>`<div class="ranking-row"><span class="rank">${i+1}</span><div><strong>${esc(r.name)}</strong><small>${r.correct}/5 rätt · utslag ${r.tie}</small></div><strong>${r.correct} rätt</strong></div>`).join(''):'<div class="empty">Topplistan fylls på när någon skickar in.</div>'}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active','active-view'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active-view')});
$('#new-team').onclick=()=>{const team={id:crypto.randomUUID(),name:'Nytt lag',members:[{name:'',scores:[0,0,0,0,0]}]};state.teams.push(team);selectedTeamId=team.id;localStorage.setItem(TEAM_KEY,selectedTeamId);save();renderTeams();renderLeaderboard()};
$('#save-quiz').onclick=async()=>{const name=$('#quiz-name').value.trim();if(!name)return alert('Skriv ditt namn först.');const picks=questions.map((_,i)=>document.querySelector(`input[name=q${i}]:checked`)?.value);if(picks.some(x=>!x))return alert('Svara på alla fem frågor.');const entry={id:crypto.randomUUID(),name,correct:picks.filter((x,i)=>x===answers[i]).length,tie:+$('#tie-break').value||0};state.quizzes.push(entry);save();if(remote)try{await request('quiz_entries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:entry.id,event_code:cfg.eventCode,name:entry.name,correct:entry.correct,tie_break:entry.tie})})}catch{}renderQuiz();$('#quiz-name').value='';$('#tie-break').value='';document.querySelectorAll('input[type=radio]').forEach(x=>x.checked=false)};
$('#export-data').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='teamday-resultat.json';a.click();URL.revokeObjectURL(a.href)};
$('#import-file').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{state=JSON.parse(reader.result);save();renderTeams();renderLeaderboard();renderQuiz()}catch{alert('Filen kunde inte läsas.')}};reader.readAsText(file)};
$('#clear-data').onclick=()=>{if(confirm('Rensa alla lokala resultat?')){localStorage.removeItem(KEY);location.reload()}};
renderTeams();renderLeaderboard();renderQuiz();loadRemote();
