const KEY='oas-teamday-v1', TEAM_KEY='oas-teamday-selected-team', VIEW_KEY='oas-teamday-view', cfg=window.TEAMDAY_CONFIG||{};
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const remote=Boolean(cfg.url&&cfg.anonKey), apiBase=remote?`${cfg.url.replace(/\/$/,'')}/rest/v1`:'';
let syncTimer, ready=!remote, state=JSON.parse(localStorage.getItem(KEY)||'null')||{teams:[{id:crypto.randomUUID(),name:'Lag 1',members:[{name:'',scores:[0,0,0,0,0]}]}],quizzes:[]};
state.teams.forEach(t=>{t.id??=crypto.randomUUID();t.members.forEach(m=>m.scores=[0,0,0,0,0].map((_,i)=>m.scores?.[i]||0))});
let selectedTeamId=localStorage.getItem(TEAM_KEY)||(state.teams.length===1?state.teams[0].id:'');
const setStatus=(text,kind='')=>{const el=$('#sync-status');el.textContent=text;el.className=`sync-status ${kind}`};
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));if(remote){setStatus('Sparat lokalt · synkar…','busy');clearTimeout(syncTimer);syncTimer=setTimeout(syncAll,500)}};
async function request(path,options={}){const r=await fetch(`${apiBase}/${path}`,{...options,headers:{apikey:cfg.anonKey,Authorization:`Bearer ${cfg.anonKey}`,Prefer:'return=minimal',...(options.headers||{})}});const body=await r.text();if(!r.ok)throw Error(body);return body?JSON.parse(body):null}
async function syncAll(){try{for(const t of state.teams)await request('team_cards',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal','Content-Type':'application/json'},body:JSON.stringify({id:t.id,event_code:cfg.eventCode,name:t.name,members:t.members,updated_at:new Date().toISOString()})});setStatus('Synkad','ok')}catch(e){setStatus('Ej synkad · sparat lokalt','error')}}
async function loadRemote(){if(!remote){setStatus('Lokal lagring');return}try{const teams=await request(`team_cards?event_code=eq.${encodeURIComponent(cfg.eventCode)}&order=updated_at.asc`,{headers:{Prefer:'return=representation'}});state.teams=teams.map(t=>({id:t.id,name:t.name,members:t.members}));selectedTeamId=state.teams.some(t=>t.id===selectedTeamId)?selectedTeamId:(state.teams.length===1?state.teams[0].id:'');localStorage.setItem(KEY,JSON.stringify(state));setStatus('Synkad','ok')}catch(e){setStatus('Offline · lokalt läge','error')}finally{ready=true}}
function renderTeamPicker(){const picker=$('#team-picker');picker.innerHTML='<option value="">Välj ditt lag…</option>'+state.teams.map(t=>`<option value="${t.id}">${esc(t.name||'Namnlöst lag')}</option>`).join('');picker.value=state.teams.some(t=>t.id===selectedTeamId)?selectedTeamId:'';picker.onchange=e=>{selectedTeamId=e.target.value;localStorage.setItem(TEAM_KEY,selectedTeamId);$('#team-detail').innerHTML='';delete $('#team-detail').dataset.teamId;renderTeams();renderLeaderboard()}}
function renderTeams(){const list=$('#team-list');list.innerHTML='';renderTeamPicker();const team=state.teams.find(t=>t.id===selectedTeamId);if(!team){list.innerHTML='<div class="card empty">Välj ditt lag ovan för att öppna scorekortet.</div>';return}const ti=state.teams.indexOf(team),card=$('#team-template').content.cloneNode(true),el=card.querySelector('.team-card');card.querySelector('.team-number').textContent=ti+1;const name=card.querySelector('.team-name');name.value=team.name;name.oninput=e=>{team.name=e.target.value;save();renderTeamPicker();renderLeaderboard()};const members=card.querySelector('.members');const updateTotal=()=>{el.querySelector('.team-total').textContent=team.members.reduce((a,m)=>a+m.scores.reduce((x,v)=>x+(+v||0),0),0)+' p'};team.members.forEach((m,mi)=>{const row=$('#member-template').content.cloneNode(true),n=row.querySelector('.member-name');n.value=m.name;n.oninput=e=>{m.name=e.target.value;save()};row.querySelectorAll('.score').forEach(s=>{const b=+s.dataset.branch;s.value=m.scores[b]||0;s.oninput=e=>{m.scores[b]=+e.target.value||0;save();updateTotal();renderLeaderboard()}});row.querySelector('.delete-member').onclick=()=>{team.members.splice(mi,1);save();renderTeams()};members.append(row)});updateTotal();card.querySelector('.add-member').onclick=()=>{team.members.push({name:'',scores:[0,0,0,0,0]});save();renderTeams()};list.append(card)}
function renderLeaderboard(){const rows=state.teams.map(t=>({team:t,name:t.name||'Namnlöst lag',score:t.members.reduce((a,m)=>a+m.scores.reduce((x,v)=>x+(+v||0),0),0)})).sort((a,b)=>b.score-a.score);$('#leaderboard').innerHTML=rows.length?rows.map((r,i)=>`<div class="ranking-row"><span class="rank">${i+1}</span><div><button class="team-link" data-team-id="${r.team.id}"><strong>${esc(r.name)}</strong><small>${i===0?'Leder just nu · klicka för detaljer':'Klicka för detaljer'}</small></button></div><strong>${r.score} p</strong></div>`).join(''):'<div class="empty">Inga lag ännu.</div>';document.querySelectorAll('.team-link').forEach(b=>b.onclick=()=>showTeam(b.dataset.teamId))}
function showTeam(id){const detail=$('#team-detail');if(detail.dataset.teamId===id){detail.innerHTML='';delete detail.dataset.teamId;return}const team=state.teams.find(t=>t.id===id);if(!team)return;const total=team.members.reduce((a,m)=>a+m.scores.reduce((x,v)=>x+(+v||0),0),0);detail.dataset.teamId=id;detail.innerHTML=`<h3>${esc(team.name||'Namnlöst lag')} · ${total} p</h3><table class="detail-table"><thead><tr><th>Deltagare</th><th>Pilbåge</th><th>Lasso</th><th>Luftpistol</th><th>Hästskor</th><th>Balans</th><th>Totalt</th></tr></thead><tbody>${team.members.map(m=>`<tr><td>${esc(m.name||'Namnlös')}</td>${m.scores.map(s=>`<td>${+s||0}</td>`).join('')}<td><strong>${m.scores.reduce((a,v)=>a+(+v||0),0)}</strong></td></tr>`).join('')}</tbody></table>`}
const showView=view=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active','active-view'));document.querySelector(`.tab[data-view="${view}"]`)?.classList.add('active');$('#'+view)?.classList.add('active-view');localStorage.setItem(VIEW_KEY,view)};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showView(b.dataset.view));showView(localStorage.getItem(VIEW_KEY)||'femkamp');
async function start(){if(remote){setStatus('Laddar…','busy');await loadRemote()}renderTeams();renderLeaderboard()}start();
